import {CORE_SCHOOLS,type MealRecord,type Action} from './model';
export const SHEET_URL='https://docs.google.com/spreadsheets/d/1NF5RyZT49ZMj9FrEKcWSyWZND6-aJyNsYVWtVXkR6FA/edit';
const ROOT='https://docs.google.com/spreadsheets/d/e/2PACX-1vTYU2WSUX1hiXTTbSl8G9nn5iv_KapFNsXss0jRcrVzPEVDDn3vNu6jtdO2K_fna-6NNrblPXObJXMt/pub';
const MEALS=ROOT+'?gid=2096856930&single=true&output=csv';
const ACTIONS=ROOT+'?gid=2049113068&single=true&output=csv';
export function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell.length){throw Error('試算表CSV格式異常');}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('試算表CSV引號未閉合');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);const headers=rows.shift()?.map(v=>v.replace(/^\uFEFF/,'').trim())||[];if(new Set(headers).size!==headers.length)throw Error('試算表欄名重複');return {headers,rows:rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])))};}
function date(v:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)throw Error('試算表日期需使用yyyy-mm-dd格式');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(v>today)throw Error('試算表包含未來日期，請先核對');return v;}
function number(v:string,max:number){if(!v.trim()||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>max)throw Error('試算表人數或重量欄位有缺漏或異常');return Number(v);}
function school(v:string){if(!CORE_SCHOOLS.some(s=>s.id===v))throw Error('試算表學校代碼尚未加入網站名單');return v;}
function requireHeaders(actual:string[],expected:string[]){if(expected.some(h=>!actual.includes(h)))throw Error('Google試算表公開欄位已變更，請確認表頭');}
export function parseMeals(text:string):MealRecord[]{const csv=parseCsv(text);requireHeaders(csv.headers,['date','schoolId','cohort','phase','participants','plateG','unservedG','inedibleG','version','updatedAt']);const seen=new Set<string>();return csv.rows.filter(r=>Object.values(r).some(Boolean)).map(r=>{const participants=number(r.participants,10000);if(!Number.isInteger(participants)||participants<1)throw Error('試算表用餐人數需為正整數');if(!r.cohort||!r.version||!['baseline','action','followup'].includes(r.phase))throw Error('試算表缺少量測範圍、期別或教案版本');const d=date(r.date),s=school(r.schoolId),key=JSON.stringify([s,d,r.cohort]);if(seen.has(key))throw Error('同一學校、日期、量測範圍有重複紀錄，請修正試算表');seen.add(key);return {id:'sheets-'+key,schoolId:s,date:d,cohort:r.cohort,phase:r.phase as MealRecord['phase'],participants,plateG:number(r.plateG,10000000),unservedG:number(r.unservedG,10000000),inedibleG:r.inedibleG===''?null:number(r.inedibleG,10000000),version:r.version,menu:'',note:'',updatedAt:r.updatedAt||''};});}
export function parseActions(text:string):Action[]{const csv=parseCsv(text);requireHeaders(csv.headers,['date','schoolId','title','body','lesson']);return csv.rows.filter(r=>Object.values(r).some(Boolean)).map((r,i)=>{const lesson=number(r.lesson,12);if(!Number.isInteger(lesson)||lesson<1||!r.title||!r.body)throw Error('試算表行動資料缺少標題、內容或有效節次');return {id:'sheets-action-'+i,schoolId:school(r.schoolId),date:date(r.date),title:r.title,body:r.body,lesson};});}
export async function loadPlatformData(){async function read(url:string){const r=await fetch(url,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('暫時無法讀取Google試算表，請稍後重新整理');if(!(r.headers.get('content-type')||'').includes('text/csv'))throw Error('Google公開分頁未發布為CSV，請確認發布設定');return r.text();}const [meals,actions]=await Promise.all([read(MEALS),read(ACTIONS)]);return {schools:CORE_SCHOOLS,records:parseMeals(meals),actions:parseActions(actions),access:{signedIn:false,admin:false,schoolId:null,approved:false},requests:[],syncedAt:new Date().toISOString()};}
